Add .limit=10 to wsearch
codalab/codalab-worksheets pull request #1353
Opened 2019-09-05 09:37 UTC by candicegjing

This PR implemented features in #1350 .

2019-09-05 14:15 UTC, percyliang requested changes
I don't actually see the logic to do the .limit....

2019-09-05 14:15 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +            '  wls .limit=10           : Limit the number of results to the top 10.',
Make it clear in the help message that we're limiting to top 10 results (perhaps on the first line).

2019-09-07 09:51 UTC, candicegjing commented
I think `.limit` function is already implemented in the code. I updated its default value to be 10.

2019-09-07 20:44 UTC, percyliang approved these changes

2019-09-08 00:55 UTC, merged