redirect error report to slack channel
codalab/codalab-worksheets pull request #1455
Opened 2019-10-02 22:27 UTC by candicegjing

Fixed #1449 
Still need to decide whose token to use.

2019-10-03 06:32 UTC, percyliang requested changes
There are other parts of the codebase that send email (e.g., when there are exceptions thrown), which should have slack added.

2019-10-03 06:32 UTC, percyliang commented on monitor.py
> +#!/usr/bin/python3
I think using `/usr/bin/env` is better

2019-10-03 06:32 UTC, percyliang commented on monitor.py
> +def send_slack_notification(subject, message):
Should factor this out into a separate `slack.py` file that can be used by other parts of the codebase.

2019-10-03 06:32 UTC, percyliang commented on monitor.py
> -        send_email('%s [%d times]' % (error_type, n), s.split('\n'))
I don't think we want to get rid of email.  There are some installations where people don't use slack

2019-10-04 23:29 UTC, epicfaace commented
Looking into this and maybe another way to do this is to _keep_ the e-mail integration. Slack can give you a special email address, and if you send emails to that address, the messages will show up in a particular channel (https://codalab.slack.com/apps/A0F81496D-email)

Not sure which way is better, though. It might be easier for deployment if we don't have to manage more variables such as the slack API key, but on the other hand, if we are going to have more deep slack integration in the future, it would be good to continue integrating directly via Slack's API.

2019-10-05 01:16 UTC, percyliang commented
Oh, I think if we can just do it via email, maybe we should just do that, since it minimizes the number of dependencies we have?

2019-10-06 00:00 UTC, candicegjing commented
Yes, I agree. If we can do it through email, we should use it. @percyliang Then for this ticket, should I just close this PR and set up the email configuration?

2019-10-06 00:53 UTC, percyliang commented
Yes, maybe convert this ticket into just some documentation on how to setup
Slack via email.

On Sat, Oct 5, 2019 at 5:00 PM Jing Ge <notifications@github.com> wrote:

> Yes, I agree. If we can do it through email, we should use it. @percyliang
> <https://github.com/percyliang> Then for this ticket, should I just close
> this PR and set up the email configuration?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codalab/codalab-worksheets/pull/1455?email_source=notifications&email_token=AADKJOAQZK33MKOXDKRGN73QNETBDA5CNFSM4I44FBZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAN6KUA#issuecomment-538699088>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADKJOFLNDVLCUMAN2JDPDTQNETBDANCNFSM4I44FBZA>
> .
>

2019-10-11 20:22 UTC, candicegjing commented
<img width="686" alt="Screen Shot 2019-10-11 at 1 21 56 PM" src="https://user-images.githubusercontent.com/1483372/66682505-254b8a80-ec2a-11e9-9b3f-5f847a1ddf3a.png">

2019-10-12 00:30 UTC, epicfaace reviewed
Will we need to modify https://github.com/codalab/codalab-worksheets/blob/master/monitor.py too?

2019-10-12 20:26 UTC, percyliang requested changes
I don't think we need a code change here...just change our admin_email to point to slack.

2019-10-24 02:57 UTC, percyliang commented on docker/compose_files/docker-compose.yml
> +  worker-shared-file-system:
Why does this show up in this PR?

2019-10-24 02:58 UTC, percyliang commented on docs/Server-Setup.md
> +If you need to send Slack notification from monitoring service, there are two ways to configure your system.
"Slack notifications from the `monitor.py` service"

2019-10-24 02:58 UTC, percyliang commented on docs/Server-Setup.md
> +1. Using Slack rest API
We don't support this, right?  Delete?

2019-10-24 03:00 UTC, percyliang commented on docs/Server-Setup.md
> +1. Using Slack Email App
Give more context: say "System notifications (e.g., monitor.py) are sent to `$ADMIN_EMAIL`.  If you're using Slack, then you can set $ADMIN_EMAIL to a special email address which will show up in a designated slack channel.  See X for more details.  Note that this works only with the standard plan."

2019-11-14 00:57 UTC, percyliang requested changes
I think this should not be labeled as ADMIN versus SLACK but rather as MONITOR (automatic messages that we don't reply to - happen to go to slack) and HELP (messages from users - happen to go to gmail).

2019-11-20 18:58 UTC, percyliang reviewed
The prod/dev distinction should not appear in the codalab-worksheets repo.  It should be a configuration in our deployment repo.

2019-11-22 06:04 UTC, percyliang commented on codalab_service.py
> +    CodalabArg(name='help_email', help='Help email to send user questions to'),
Maybe call this `admin_email` and `support_email` to use consistent terminology with what's used in the `config.json` file.

2019-11-23 05:15 UTC, candicegjing commented
Closed via #1449

2019-11-23 05:16 UTC, merged