When a item is selected, the highlight color now occupies whole row
codalab/codalab-worksheets pull request #1466
Opened 2019-10-03 06:50 UTC by yipenghe

Fix #1459 

To test: checkout to this branch and select any block

![highlight-example2](https://user-images.githubusercontent.com/23012631/66105075-4bf52b80-e56f-11e9-8cb0-ec46fc6325ce.png)
![hightlight-example](https://user-images.githubusercontent.com/23012631/66105076-4bf52b80-e56f-11e9-9074-39860bb8ef63.png)

2019-10-04 23:22 UTC, epicfaace requested changes

2019-10-04 23:22 UTC, epicfaace commented on frontend/src/css/imports.css
> +  width:100%;
```suggestion
  width: 100%;
```

2019-10-04 23:22 UTC, epicfaace approved these changes

2019-10-04 23:30 UTC, epicfaace reviewed
If you notice, the old UI on worksheets.codalab.org had slightly blurred edges. If possible, could you also add those in here?

![image](https://user-images.githubusercontent.com/1689183/66245679-4c530b00-e6c4-11e9-9536-430589784130.png)

2019-10-05 04:09 UTC, yipenghe commented
> If you notice, the old UI on worksheets.codalab.org had slightly blurred edges. If possible, could you also add those in here?
> 
> ![image](https://user-images.githubusercontent.com/1689183/66245679-4c530b00-e6c4-11e9-9536-430589784130.png)

I will do it in a separate PR

2019-10-05 04:09 UTC, merged