Change display of run time for bundles
codalab/codalab-worksheets pull request #1475
Opened 2019-10-05 21:32 UTC by yipenghe

Addressing #1199 
1. Changed to display run time below the command and positioned to right so it won't be the first information that comes to eye
2. Truncate the time to show at most 5 decimals, run time smaller than 0.00001s will just show '< 0.00001s' instead
3. Added a clock icon

![Screenshot from 2019-10-05 14-24-56](https://user-images.githubusercontent.com/23012631/66261103-82ec5c80-e77c-11e9-8cd2-85d1697fda1f.png)
![Screenshot from 2019-10-05 14-25-00](https://user-images.githubusercontent.com/23012631/66261104-8384f300-e77c-11e9-99be-c26f2aeae681.png)

2019-10-05 21:45 UTC, yipenghe commented
Planned changes for the formatting of time

2019-10-06 02:47 UTC, percyliang requested changes
We should use the same rendering as the logic for rendering durations in `formatting.py`.  We can either pass string versions from the backend, or if that's inconvenient, just have a `Formatting.js` that parallels `formatting.py`.

2019-10-07 02:52 UTC, yipenghe commented
> We should use the same rendering as the logic for rendering durations in `formatting.py`. We can either pass string versions from the backend, or if that's inconvenient, just have a `Formatting.js` that parallels `formatting.py`.

Found a exisiting render duration function and used that

2019-10-07 04:11 UTC, percyliang approved these changes

2019-10-07 04:11 UTC, percyliang commented on frontend/src/components/worksheets/BundleDetail/MainContent.jsx
> +        //Get the correct run time display
nit: space before "Get"

2019-10-07 04:11 UTC, percyliang commented on frontend/src/components/worksheets/BundleDetail/MainContent.jsx
> +        let bundleRunTime;
Simplify: `const bundleRunTime = bundleInfo.metadata.time ? renderDuration(...) : ...`;

2019-10-07 04:38 UTC, yipenghe commented on frontend/src/components/worksheets/BundleDetail/MainContent.jsx
> +        let bundleRunTime;
Thanks, addressed!

2019-10-07 05:17 UTC, merged