Fill owner column with real value
codalab/codalab-worksheets pull request #1487
Opened 2019-10-09 04:21 UTC by candicegjing

Fixed #1344. Currently `owner_name` doesn't exist in `bundle_info` dictionary. If we want to have a real name return back. I'll find a way to transfer `owner_id` to `owner_name`,

2019-10-09 07:01 UTC, yipenghe reviewed
Can you attach a screenshot on how it looks like right now?

2019-10-09 16:01 UTC, candicegjing commented
<img width="1309" alt="Screen Shot 2019-10-09 at 8 54 18 AM" src="https://user-images.githubusercontent.com/1483372/66498671-4918a000-ea73-11e9-9007-1e7f7af65ed7.png">
It's currently filled in with `owner_id`, but I feel it's probably better to fill in with `owner_name`. I am trying to find a way to add that field in.

2019-10-09 16:10 UTC, epicfaace reviewed
Looks good -- can you also add a test? It could go something like this (with the right directives replaced, though) -- and you can test at the end to see if the rendered table contains the owner names as opposed to the ids:

```
    wuuid = run_command([cl, 'work', '-u'])
    run_command([cl, 'add', 'text', '% search'])
    check_contains(['...', run_command([cl, 'print']))
```

I think you could add it to the "worksheet_search" test module in test_cli.py

2019-10-10 17:15 UTC, candicegjing commented
I have updated the `owner_id` to `owner_name` in `owner` column. 
<img width="1006" alt="Screen Shot 2019-10-10 at 10 14 04 AM" src="https://user-images.githubusercontent.com/1483372/66590990-ce20b980-eb46-11e9-8b95-461762749d2e.png">

2019-10-10 22:47 UTC, yipenghe requested changes

2019-10-10 22:47 UTC, yipenghe commented on codalab/lib/worksheet_util.py
> +        from bottle import local
Imports are better put on top of file, see https://www.python.org/dev/peps/pep-0008/#imports

2019-10-10 22:47 UTC, yipenghe commented on codalab/lib/worksheet_util.py
> +
extra line

2019-10-11 00:44 UTC, percyliang requested changes
worksheet_util.py shouldn't depend on bottle.  An intermediate solution is passing the `model` in for now.  More generally, we need to think about efficiency...here, we have to make a DB request for each row, which might be too slow, and we might want to batch DB queries.

2019-10-13 04:43 UTC, candicegjing commented
> worksheet_util.py shouldn't depend on bottle. An intermediate solution is passing the `model` in for now. More generally, we need to think about efficiency...here, we have to make a DB request for each row, which might be too slow, and we might want to batch DB queries.

2019-10-13 04:52 UTC, candicegjing commented
For each time we load a worksheet, I personally think the bundles listed under the current worksheet are more likely to belong to the owner. Based on this intuition, I updated the PR by passing a cached dictionary to the interpret_genpath function. When we parse the `bundle_info` one by one, if we see a previously visited `owner_id`, we can directly return it, instead of making a db call. 
Another thought is that we can change the way of parsing all the entries of `bundle_infos` from `row by row` to `column by column`. Then we can get a full list of `owner` for all the bundles and send a one-time db call.

2019-10-13 04:55 UTC, percyliang commented on codalab/lib/worksheet_util.py
>      Quickly interpret the genpaths (generalized path) that only require looking
Document the new arguments.  Specifically, note what the input/output of `owner_cache` is.

2019-10-13 04:56 UTC, percyliang commented on codalab/lib/worksheet_util.py
> +            owner_cache = dict()
nit: just do `{}`

2019-10-13 04:57 UTC, percyliang approved these changes
LGTM modulo a few comments.

2019-10-13 04:57 UTC, percyliang commented on codalab/lib/worksheet_util.py
> +                owner = db_model.get_user(user_id=bundle_info['owner_id'])
Put a comment that in the future, we might want to batch this.

2019-10-13 05:07 UTC, percyliang commented
On the other hand, the main reason you'd want to display the owner column (e.g., on https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b) is when there are different owners (otherwise, why bother).

2019-10-14 02:26 UTC, merged