Update bundle detail when detail was opened in created state
codalab/codalab-worksheets pull request #2129
Opened 2020-04-02 08:42 UTC by yipenghe

Fix #2033

2020-04-08 19:22 UTC, yipenghe commented
@epicfaace Can you review?

2020-04-09 13:25 UTC, epicfaace requested changes

2020-04-09 13:25 UTC, epicfaace commented on frontend/src/components/worksheets/BundleDetail/BundleDetail.jsx
> +                    this.state.bundleInfo.state === 'created'
I think we should check for more bundle states -- in fact, use a regex `(uploading|created|staged|making|starting|preparing|running)` (comes from https://github.com/codalab/codalab-worksheets/blob/6e0d3e9faff013db8d77125329649dfec02511df/scripts/create_sample_worksheet.py#L38)

2020-04-16 02:05 UTC, epicfaace approved these changes

2020-04-16 02:09 UTC, merged