Add button to expand/shrink worksheet width
codalab/codalab-worksheets pull request #2130
Opened 2020-04-02 10:11 UTC by yipenghe

Default to use 50% of the window size, and allow to expand to 80% of the window size. Utilizes local storage to remember the preference of the expand size, so user don't need to click on expand everytime they open a new tab
![Screenshot from 2020-04-02 03-09-34](https://user-images.githubusercontent.com/23012631/78236885-79278580-748f-11ea-8fa3-c8aa1f6c299c.png)
![Screenshot from 2020-04-02 03-09-39](https://user-images.githubusercontent.com/23012631/78236890-7af14900-748f-11ea-9e0e-4b6f4b23fd3b.png)

2020-04-02 15:49 UTC, percyliang commented
Great.  Seems like the expand should essentially take up close to 100%.  For those wide tables, you really shouldn't waste any space.  Is there a way to pass the expansion mode in the URL too?

2020-04-09 13:31 UTC, epicfaace requested changes
When I click the "expand" button, it takes a second or so before the worksheet actually expands. We should disable the button so that users do not accidentally click the button twice.

Same goes for the "+" keyboard shortcut -- otherwise it's easy for the user to accidentally expand twice and then go back to the normal size.

2020-04-09 13:31 UTC, epicfaace commented on frontend/src/constants.js
> +export const EXPAND_PERCENTAGE = '90%';
Can you rename these to `EXPANDED_WORKSHEET_WIDTH` and `DEFAULT_WORKSHEET_WIDTH`?

2020-04-09 13:31 UTC, epicfaace commented on frontend/src/components/worksheets/Worksheet/Worksheet.js
> +        window.localStorage.setItem('worksheetSize', newPercentage);
Can you refactor the localStorage worksheet size item name into a constant?

2020-04-09 13:31 UTC, epicfaace commented on frontend/src/CodalabApp.js
> +                            <Route path='/worksheets/:uuid/:mode?' component={Worksheet} />
I think it would be best to remove the URL change when expanding / shrinking, given that this is a global setting that is set in localStorage.

2020-04-16 06:52 UTC, yipenghe commented
> When I click the "expand" button, it takes a second or so before the worksheet actually expands. We should disable the button so that users do not accidentally click the button twice.
> 
> Same goes for the "+" keyboard shortcut -- otherwise it's easy for the user to accidentally expand twice and then go back to the normal size.

I think this is related to how large the worksheet is, for small worksheets it seems to pretty fast. I'm not sure how to disable only when the worksheet is trying to rerender the main area, I tried to add in the onclick event to set disabling value, but the batch state update will cause the button be disabled only along with the expansion update. I feel like it's OK since clicking twice doesn't do harm

2020-04-30 18:24 UTC, epicfaace commented
> I feel like it's OK since clicking twice doesn't do harm

I also got a faster computer so this isn't really an issue for me anymore lol, so sounds good

2020-04-30 18:26 UTC, epicfaace approved these changes

2020-04-30 18:26 UTC, epicfaace commented on frontend/src/CodalabApp.js
> +                            <Route path='/worksheets/:uuid/:mode?' component={Worksheet} />
```suggestion
                            <Route path='/worksheets/:uuid' component={Worksheet} />
```

2020-04-30 21:00 UTC, merged