validate new worksheet name
codalab/codalab-worksheets pull request #2735
Opened 2020-08-10 00:53 UTC by michaeldu1

### Reasons for making this change

Previously silent error on front end 

### Related issues

fixes #2408 

### Screenshots

![Uploading Screen Shot 2020-08-09 at 7.51.19 PM.png…]()

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

2020-08-10 01:51 UTC, percyliang commented on frontend/src/components/NavBar.js
> +        if (this.state.newWorksheetName.includes(' ')) {
Can you make this logic match the backend (there's a regex)?  Put a comment to that file to keep it consistent?

2020-08-20 20:53 UTC, epicfaace commented on frontend/src/components/NavBar.js
> +const NAME_STR_REGEX = new RegExp('^[a-zA-Z_][a-zA-Z0-9_.-]*$'); // matches regex on the backend in spec_util.py
```suggestion
const NAME_STR_REGEX = /^[a-zA-Z_][a-zA-Z0-9_.-]*$/; // matches regex on the backend in spec_util.py
```

2020-08-20 20:56 UTC, epicfaace requested changes
Can you actually check the logic here with what's already in NewWorksheet.js (https://github.com/codalab/codalab-worksheets/blob/ba9ed2f032f4627b14915454daa3ef6d161c4408/frontend/src/components/worksheets/NewWorksheet.js#L59)? I wonder if that logic just needs some fixing instead of having to add new logic in NavBar.js.

2020-08-20 20:56 UTC, epicfaace commented on frontend/src/components/NavBar.js
> +const NAME_STR_REGEX = /^[a-zA-Z_][a-zA-Z0-9_.-]*$/; // matches regex on the backend in spec_util.py
Can you rename this to NAME_REGEX, and also extract this regex into constants.js? It's also declared / used in NewWorksheet.js, so we want to only define it in one place.

2020-08-20 20:56 UTC, epicfaace commented on frontend/src/components/NavBar.js
> +                snackbarMessage: `Worksheet name with name ${this.state.newWorksheetName} may not contain spaces`,
We should make the message the same as on the backend: https://github.com/codalab/codalab-worksheets/blob/69ee12fa74c0699cfe9d3f998179ef85959a5eef/codalab/lib/spec_util.py#L58

2020-08-27 20:56 UTC, epicfaace commented
> Can you actually check the logic here with what's already in NewWorksheet.js (
> 
> https://github.com/codalab/codalab-worksheets/blob/ba9ed2f032f4627b14915454daa3ef6d161c4408/frontend/src/components/worksheets/NewWorksheet.js#L59
> 
> )? I wonder if that logic just needs some fixing instead of having to add new logic in NavBar.js.


@michaeldu1 do you know if that logic I linked to in this comment is relevant at all to solving this issue? Wouldn't want there to be duplicate code for checking names if one isn't used.

2020-08-30 21:49 UTC, michaeldu1 commented
@epicfaace I don't see NewWorksheet.js used anywhere in the repo -- is it possible that this an old component?

2020-09-15 20:24 UTC, epicfaace commented
> @epicfaace I don't see NewWorksheet.js used anywhere in the repo -- is it possible that this an old component?

Yeah, that's possible. I was thinking we could remove it if we didn't need to use it; however, let's just merge this PR for now.

2020-09-15 20:24 UTC, epicfaace approved these changes

2020-09-15 20:36 UTC, merged