Create pre-commit.yml
codalab/codalab-worksheets pull request #2764
Opened 2020-08-17 00:31 UTC by yiboliu

This is to resolve #2176 by adding pre-commit.yml to workflows.

### Reasons for making this change
Add pre-commit.yml to run pre-commit.sh before commit.  

### Related issues
#2176

### Screenshots

### Checklist

* [ ] I've added a screenshot of the changes, if this is a frontend change
* [ ] I've added and/or updated tests, if this is a backend change
* [ ] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [ ] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

2020-08-17 01:00 UTC, percyliang commented on .github/workflows/pre-commit.yml
> +      run: ./pre-commit.sh
Pre-commit mutates the code, so need to check that it didn't change.  This also seems redundant with some of the checks already there...should we organize a bit better (cc @epicfaace)?

2020-08-17 01:32 UTC, epicfaace commented
@yiboliu , issue #2176 is not about adding `pre-commit.yml`. We don't want to run precommit checks automatically upon every commit, actually, because the checks can take a long time to run.

That issue is just about adding a new check in the GitHub Actions `format` job, in which we want to run `./pre-commit.sh` and make sure that no files have been changed. Sorry if that wasn't clear!

2020-08-24 02:06 UTC, epicfaace commented
@yiboliu can you please rename this PR and change the description (it might be better actually to just create a separate PR)? Additionally, you may need to run ./pre-commit.sh first to fix the formatting for CI.

2020-08-25 18:34 UTC, epicfaace commented on pre-commit.sh
> +
`python` might refer to Python 2 for many people's systems -- could you keep the original virtualenv setup on this file?

2020-08-27 13:10 UTC, epicfaace requested changes
Looks like the precommit change is failing. Can you run pre-commit.sh and then check in the changes so that the build passes?

2020-09-07 13:29 UTC, epicfaace requested changes

2020-09-07 13:29 UTC, epicfaace commented on .github/workflows/test.yml
>        - run: pip install -r requirements.dev.txt
I think you can remove this line now.

2020-09-09 00:41 UTC, epicfaace approved these changes

2020-09-09 00:55 UTC, merged