Resolve potential file not found error
codalab/codalab-worksheets pull request #2765
Opened 2020-08-17 06:22 UTC by yiboliu

### Reasons for making this change
Sometimes temp file created could be deleted and thus a FileNotFoundError occurs and the gpu worker is down. This commit applies a change suggested by [discussion forum](https://bugs.python.org/issue29573)

### Related issues
#2745

### Screenshots

### Checklist

* [ ] I've added a screenshot of the changes, if this is a frontend change
* [ ] I've added and/or updated tests, if this is a backend change
* [ ] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [ ] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

2020-08-17 06:52 UTC, teetone requested changes

2020-08-17 06:52 UTC, teetone commented on codalab/worker/state_committer.py
> +        with tempfile.NamedTemporaryFile(delete=False) as f:
Since we are setting `delete=False`, can you add a test that ensures that the temp file eventually gets deleted?

2020-08-17 06:52 UTC, teetone commented on codalab/worker/state_committer.py
> +                    logging.info("Problem occurred in creating temp file {}".format(f.name))
You actually need to get the logger with `logger = logging.getLogger(__name__)` and then use the logger to log `logger.info("something")`.

2020-08-17 06:52 UTC, teetone commented on codalab/worker/state_committer.py
> +                    logging.info("Problem occurred in creating temp file {}".format(f.name))
This error is catching when calling `os.unlink`. I think the log message should mention that instead.

2020-08-17 06:52 UTC, teetone commented on codalab/worker/state_committer.py
> +                    logging.info("Problem occurred in creating temp file {}".format(f.name))
It should also be `logger.error` instead of `logger.info`.

2020-08-17 06:52 UTC, teetone commented on codalab/worker/state_committer.py
> +                    raise
Do we need to raise an error here?

2020-08-21 07:19 UTC, teetone commented
@yiboliu Just to follow up on our meeting earlier, can you add a link to the discussion forum that suggested this solution and a comment in the code explaining why `delete=False` is needed?

2020-08-23 06:55 UTC, yiboliu commented
> @yiboliu Just to follow up on our meeting earlier, can you add a link to the discussion forum that suggested this solution and a comment in the code explaining why `delete=False` is needed?

It's already there. If you click the `discussion forum` the website will be directed.

2020-08-23 07:26 UTC, yiboliu commented on codalab/worker/state_committer.py
> +                    raise
So after I used logger.error, we shouldn't need to raise an error anymore.

2020-08-23 07:26 UTC, yiboliu commented on codalab/worker/state_committer.py
> +        with tempfile.NamedTemporaryFile(delete=False) as f:
Added. Let's see if it works

2020-08-25 05:41 UTC, teetone approved these changes

2020-08-25 05:42 UTC, teetone commented
> > @yiboliu Just to follow up on our meeting earlier, can you add a link to the discussion forum that suggested this solution and a comment in the code explaining why `delete=False` is needed?
> 
> It's already there. If you click the `discussion forum` the website will be directed.

Can you also add a comment in the code?

2020-08-27 04:19 UTC, merged