Fix none concatenation error when interpreting worksheet
codalab/codalab-worksheets pull request #3218
Opened 2021-01-25 15:29 UTC by epicfaace

### Reasons for making this change

Fixes #3217. I'm not sure exactly when / why this issue is happening, but `key` is the only possible variable here tat can be equal to `None`, so we might as well just give it a fallback to an empty string if it is equal to `None` so that it doesn't cause this error.

2021-01-31 09:36 UTC, yiboliu requested changes
Can we use some more descriptive text as the default? Something like `missing child_path and parent_name` could tell us more insight about what's going on.

2021-01-31 14:50 UTC, epicfaace commented
I'm not exactly sure why this error is happening, i.e. in what instances `parent_name` will not be defined. I think if / once we know why this is happening, we'll better know what to put as a default value.

2021-01-31 14:50 UTC, epicfaace commented
Also, I just changed this PR to fallback to a string "None" instead of an empty string.

2021-02-01 07:13 UTC, yiboliu commented
> Also, I just changed this PR to fallback to a string "None" instead of an empty string.

Cool I think 'None' is good enough.

2021-02-01 07:13 UTC, yiboliu approved these changes

2021-02-01 08:35 UTC, teetone approved these changes

2021-02-01 14:10 UTC, merged