fix docker image status issue
codalab/codalab-worksheets pull request #3382
Opened 2021-04-06 02:04 UTC by adiprerepa

fixes the issue found by the stress test: https://worksheets-dev.codalab.org/bundles/0x25eb6936b59e463c95cf884caa0e4f7f

the error was:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/codalab/worker/docker_image_manager.py", line 253, in download
    / line['progressDetail']['total']
KeyError: 'total'
```

This checks for the key `total`

2021-04-06 16:26 UTC, epicfaace reviewed
Looks good -- can you explain a bit how this error would have led to the `'message'` error message that showed up on the stress test result?

2021-04-06 16:26 UTC, epicfaace commented on codalab/worker/docker_image_manager.py
> +                                and 'total' in line['progressDetail']
We also need to ensure that `'current'` is in `line['progressDetail']`

2021-04-06 16:26 UTC, epicfaace approved these changes

2021-04-09 16:14 UTC, epicfaace approved these changes

2021-04-09 16:14 UTC, epicfaace requested changes
Can you make the changes I requested?

2021-04-09 16:17 UTC, epicfaace commented
> can you explain a bit how this error would have led to the `'message'` error message that showed up on the stress test result?

@adiprerepa can you explain a bit about what you think regarding this question?

2021-04-09 20:57 UTC, adiprerepa commented
> > can you explain a bit how this error would have led to the `'message'` error message that showed up on the stress test result?
> 
> @adiprerepa can you explain a bit about what you think regarding this question?

Not really sure. I think it comes from https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/docker_image_manager.py#L261, and we access `_downloading[image_spec]`, which returns 'message', as opposed to accessing `_downloading[image_spec]['message']`. I have to look into it for where it's actually called, though.

Does this issue block this PR, though? Can we merge this one?

2021-04-11 21:06 UTC, epicfaace commented
1. Make sure GHA builds the docker images
2. Deploy this branch to dev (venv/bin/...) (set the codalab_version to the branch name - redostats)
3. Run stress tests

2021-04-14 05:21 UTC, adiprerepa commented
OK, deployed to dev, running stress tests now

2021-04-15 05:47 UTC, adiprerepa commented
stress tests didnt pass, but interestingly, they didnt pass even before I deployed fix-docker-image-download
Before deploy: https://github.com/codalab/codalab-worksheets/actions/runs/746356708
After deploy: https://github.com/codalab/codalab-worksheets/actions/runs/747138730
Interestingly, same error. I wonder if it's something else...

2021-04-15 05:49 UTC, adiprerepa commented
Seems to fail because of a `401 Unauthorized` which is weird because this doesn't touch anything near the `cl wait` endpoint.

Error:
```
>> cl wait 0x509b80d1e59d4a6da5eb30fce28a1aec
WARNING:retry.api:HTTP Error 401: Unauthorized, retrying in 1 seconds...
```

2021-04-15 05:51 UTC, adiprerepa commented
@epicfaace thoughts?

2021-04-20 16:28 UTC, adiprerepa commented
stress tests arent passing becuase dev is down, blocked...

2021-04-30 06:21 UTC, adiprerepa commented
https://github.com/codalab/codalab-worksheets/actions/runs/798463255

@epicfaace stress tests pass, can we merge this?

2021-04-30 19:44 UTC, epicfaace approved these changes

2021-04-30 20:11 UTC, merged