Improve handling if user does not have access to the server
codalab/codalab-worksheets pull request #3982
Opened 2022-02-01 01:12 UTC by jzwang43

### Reasons for making this change

    User creates an account on cs324.codalab.org
    User gets ugly experience (can't create worksheets, etc.)

### Related issues

Fixes #3961 

### Screenshots

Shows alert if user doesn't have access to the server:
![image](https://user-images.githubusercontent.com/29891066/151898544-55d5abf8-f6af-4b0f-b2c5-d6701d375a2b.png)

Disable interactions:

![image](https://user-images.githubusercontent.com/29891066/151898569-67baea56-2cc1-411f-bb03-9bc7e704b8ce.png)

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

2022-02-01 18:51 UTC, epicfaace commented
Let's show an error message like in https://worksheets.codalab.org/worksheets/0xbd86869844074a02aced04b5959153 for consistency:

![image](https://user-images.githubusercontent.com/1689183/152031976-33689fd0-e785-4f1a-bbc5-af0587c062ca.png)

2022-02-04 20:24 UTC, pranavjain commented
@jzwang43 Are some unit tests still failing?

2022-02-04 20:47 UTC, jzwang43 commented
> @jzwang43 Are some unit tests still failing?

Seems to be a test issue not with the dockerfiles that I fixed.

2022-02-05 04:54 UTC, pranavjain commented
Is this related to the test cases you and Ashwin wrote? What is the next step? @jzwang43 
Do let me know if you need some help in getting unblocked.

2022-02-07 17:54 UTC, jzwang43 commented
> Let's show an error message like in https://worksheets.codalab.org/worksheets/0xbd86869844074a02aced04b5959153 for consistency:
> 
> ![image](https://user-images.githubusercontent.com/1689183/152031976-33689fd0-e785-4f1a-bbc5-af0587c062ca.png)

@epicfaace I have updated the code to use the error message you mentioned. Can I get a review on this? Thanks.

2022-02-07 19:04 UTC, epicfaace requested changes

2022-02-07 19:04 UTC, epicfaace commented on codalab/rest/schemas.py
> +    has_access = fields.String(allow_none=False)
This should be a Boolean I think

2022-02-07 19:34 UTC, epicfaace approved these changes

2022-02-07 20:17 UTC, merged