Use signed URL to bypass server for GCS downloads
codalab/codalab-worksheets pull request #4070
Opened 2022-04-19 04:05 UTC by wwwjn

### Reasons for making this change
When user download bundles stored in GCS, need to bypass server to speed up the downloading process.
For now, we only support the following situation to bypass server.
<img width="885" alt="image" src="https://user-images.githubusercontent.com/40016222/163916594-2fd126a2-1d51-41d3-9109-6d9d8b3f3e64.png">

We can not support bypassing server when download a single-file bundle. This is because GCS can not support transparent decompression without setting GCS object metadata. For a detailed test process and explanation, please refer to: https://docs.google.com/document/d/1q2zTXFPlkjnm-xm6_IcfenAm5twBsYOIEdopxEHCbx0/edit#

### Related issues
Finish part of the issue #3974. Still need to bypass server when uploading file to GCS.

### Screenshots
By inspecting the frontend, we can see the redirected url and request/response when bypass server downloading.
![test3](https://user-images.githubusercontent.com/40016222/163917708-7c4fe792-25f6-45ec-9668-7024968e4c04.gif)

### Checklist

* [ ] I've added a screenshot of the changes, if this is a frontend change
* [ ] I've added and/or updated tests, if this is a backend change
* [ ] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [ ] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

2022-04-19 11:44 UTC, epicfaace reviewed
Should we add a test in `test_cli.py`? Maybe we should test it with a real GCS bucket.

2022-04-19 11:44 UTC, epicfaace commented on codalab/common.py
> +        print(kwargs, type(kwargs))
rm this

2022-04-19 17:27 UTC, wwwjn commented
> 

Yes I'm also trying to do this. I noticed that there are a lot of test cases about Azure but only a few about GCS. I'm considering how to use credential to write some test cases and test a real GCS bucket.

2022-04-22 19:51 UTC, epicfaace commented
- See if we can monkey-patch GcsIO to allow using the local client, and if the e2e tests pass.
- If they work, then add the e2e tests. Merge this PR.
- Otherwise, let's not add the e2e tests. Make an issue to add GCS e2e tests. Maybe also make issues in the upstream open source repos (gcs-emulator / apache beam). Merge this PR.

2022-04-26 19:19 UTC, epicfaace requested changes
Let's do a manual test where we set:
- CODALAB_DEFAULT_BUNDLE_STORE_NAME=gcs
- CODALAB_GOOGLE_APPLICATION_CREDENTIALS
and we should run these tests: https://github.com/codalab/codalab-worksheets/blob/master/.github/workflows/test.yml#L423-L434


Add a section to the [testing page](https://codalab-worksheets.readthedocs.io/en/latest/Server-Setup/#testing) called "manual tests" and then include the instructions to run this GCS test.

Don't add to github actions / CI.

2022-04-30 03:12 UTC, wwwjn commented
Add manual local tests to test directly using GCS, and the test result are in `.out` files: (have removed these file in final PR)
https://github.com/codalab/codalab-worksheets/pull/4070/commits/1fad99c58a40db772f2ceef0b031841628904756

Test Summary:
- Using GCS: Tests failed: upload2, blob, default_bundle_store, uls, time, link, worksheets, protected_mode
-  Not using GCS: Tests failed: blob, uls, time, link, worksheets, protected_mode

Analysis: 
- Fail upload2: Because test `upload2` checks the response header (need `Content-Encoding='identity'`), but the GCS response header does not contain `content-encoding`.
- Fail default_bundle_store:  the `default_bundle_store` test is expected to fail because it wants to create a new disk bundle storage that has the same name as our manually created one.

2022-05-02 15:51 UTC, epicfaace commented
Hmm, why are `blob, uls, time, link, worksheets, protected_mode` failing?

2022-05-02 17:14 UTC, wwwjn commented
> 

They failed because of the same reason `WARNING:retry.api:HTTP Error 403: Forbidden, retrying in 1 seconds...` Because they receive HTTP Error 403 after retry. I haven't look into detail about this test, but when I first set up my codalab, these tests fail. (It also might be because I use some wrong parameters..)

2022-05-03 19:11 UTC, epicfaace commented on docs/Server-Setup.md
> +    cl store ls  # make sure you have succcessfully add the
fix comment

2022-05-04 17:37 UTC, epicfaace approved these changes

2022-05-10 19:12 UTC, epicfaace commented on docs/Server-Setup.md
> +    cl store ls  # make sure you have succcessfully add the
@wwwjn can you update this comment, and then merge?

2022-05-10 20:17 UTC, epicfaace commented
@wwwjn feel free to merge (or add the `ready-to-merge` tag)!

2022-05-10 23:28 UTC, merged