Replace google.com with recaptcha.net
codalab/codalab-worksheets pull request #4284
Opened 2022-10-18 20:53 UTC by yifanmai

### Reasons for making this change

This allows reCaptcha to be usable from within China. Refer to the [reCaptcha documentation](https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally).

### Related issues

- Addresses #3698
- Addresses #4278 

### Screenshots

Accounts page is unchanged.

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

2022-10-19 00:44 UTC, percyliang approved these changes

2022-10-25 18:27 UTC, epicfaace requested changes

2022-10-25 18:27 UTC, epicfaace commented on codalab/rest/account.py
> +        url = 'https://www.recaptcha.net/recaptcha/api/siteverify'
What is https://www.recaptcha.net? Do you have an info page on what it's used for / who runs it / how it uses data?

2022-10-25 18:27 UTC, epicfaace approved these changes

2022-10-25 18:27 UTC, epicfaace commented on codalab/rest/account.py
> +        url = 'https://www.recaptcha.net/recaptcha/api/siteverify'
Oh I found it, it's google. Can you link to https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally in the comments?

2022-11-02 16:44 UTC, yifanmai commented
I'll rebase this branch.

2022-11-02 17:26 UTC, merged