Provides an option not to ignore patterns like .git, hidden files and…
codalab/codalab-worksheets pull request #4578
Opened 2023-11-15 08:33 UTC by HidyHan

… MACOSX files.

### Reasons for making this change

Needed for the blob storage migration, because once upon a time these files were uploaded as part of bundles. Omitting them will cause discrepancy in bundles after the migration.

### Related issues

fixes #4575

### Checklist

* [NA] I've added a screenshot of the changes, if this is a frontend change
* [Y] I've added and/or updated tests, if this is a backend change
* [Y] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [NA] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

2023-11-21 06:02 UTC, AndrewJGaut reviewed
This looks GREAT! Only thing is can we do the same thing for `zip_directory` [here](https://github.com/codalab/codalab-worksheets/blob/ignore-patterns/codalab/worker/file_util.py#L101) if possible? After that change, I think this is definitely good to go. Love the code styling for the test, too -- it's super clean!

2023-11-22 18:33 UTC, AndrewJGaut requested changes
This looks GREAT! Only thing is can we do the same thing for `zip_directory` [here](https://github.com/codalab/codalab-worksheets/blob/ignore-patterns/codalab/worker/file_util.py#L101) if possible? After that change, I think this is definitely good to go. Love the code styling for the test, too -- it's super clean!

2023-11-27 01:52 UTC, HidyHan commented
Done. zip_directory appears to be dead code, but updated it to avoid confusion.

2023-11-29 05:46 UTC, AndrewJGaut approved these changes
Looks great!

2023-11-29 05:46 UTC, merged