Send notifications
codalab/codalab-worksheets pull request #604
Opened 2016-10-29 00:45 UTC by yashsavani

Fixes codalab/codalab-worksheets#215. Added a send_notifications column to the database so that we can select users to send codalab emails to. Also set up signup form to have a checkbox for the user to select whether they want to receive emails.

2016-10-29 04:14 UTC, percyliang commented
Need to fix unit test

2016-11-08 02:17 UTC, percyliang requested changes

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +            )
append / flush to list of people sent

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +            print "%s <%s>"%(name,email)
fix whitespace

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +                .where(cl_user.c.send_some_notifications == 1)) .fetchall()
remove whitespace

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +# send_email("ysavani@stanford.edu", "Hello, World!", "Try this on for size.")
remove this

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +    subject = args.subject or "none"
single quotes

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +            manager.emailer.send_email(
print out things to stdout statistics (number sent, number remaining, number total)

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +                .where(cl_user.c.send_some_notifications == 1)) .fetchall()
make it a command-line argument to check the some or all flag

2016-11-08 02:17 UTC, percyliang commented on scripts/send_email.py
> +                .where(cl_user.c.send_some_notifications == 1)) .fetchall()
make this 0, 1, 2

2016-11-12 01:41 UTC, yashsavani commented
@percyliang: Made requested changes please take a look.

2016-11-12 03:45 UTC, percyliang commented on codalab/rest/account.py
> +        username, email, first_name, last_name, password, affiliation, 2
Define `SEND_NOTIFICATIONS_ALL` instead of use bare constants....  (see how PERMISSIONS is defined)

2016-11-12 03:46 UTC, percyliang requested changes

2016-11-12 03:46 UTC, percyliang commented on codalab/rest/schemas.py
> +    send_all_notifications = fields.Boolean()
delete unused

2016-11-12 03:46 UTC, percyliang commented on scripts/send_email.py
> +            .where(cl_user.c.send_notifications_flag%2 if get_all else\
put whitespace between %

2016-11-12 03:46 UTC, percyliang commented on tests/objects/user_test.py
> +    "send_notifications_flag": 3
define constant

2016-11-12 09:07 UTC, yashsavani commented
@percyliang Made required changes. Not sure if I completely understand the permissions method. But take a look. If it still seems off, I'll chat with Stephen about how permissions are set.

2017-01-11 16:11 UTC, percyliang commented
@yashsavani Can we get this resolved and merged ASAP?

2017-01-16 21:54 UTC, merged