Fix for displaying [Object object] for empty files
codalab/codalab-worksheets pull request #628
Opened 2017-01-08 08:22 UTC by maxwang7

Issue description: https://github.com/codalab/codalab-worksheets/issues/222

The problem I found was that in the interpret_file_gen() function, an info dictionary is built with information that is later used to form the output string, but when the info dictionary is an empty dictionary it is not properly processed. So, I simply set info to None if it is an empty dictionary.

Some things I would like comments on:
- [ ] Should I set info to None at the position I have it now or instead after line 470? I see arguments as to why that would be the more appropriate place for this code.
- [ ] Should I unit test this change? The test coverage on this file doesn't seem to cover this function yet: https://github.com/codalab/codalab-cli/blob/f33ff172db28f592aac97cf75c0911040ac3bf22/tests/lib/worksheet_util_test.py.

@percyliang @kashizui

2017-01-08 08:36 UTC, maxwang7 commented
I didn't make a time estimate beforehand, it probably would've been 2-3 hours, but my work up to this point took 5-6 hours.

2017-01-08 15:17 UTC, percyliang requested changes
Great - should be a simple change.

@kashizui I think we can get rid of lines 430, 432-434, right?

2017-01-08 15:17 UTC, percyliang commented on codalab/lib/worksheet_util.py
> +                info = None
In general, we want `info` to preserve information about the file, so don't want to just set it to None.  What's happening here is that `contents = []`.  In this case, we shouldn't be interpreting this as a TSV file, but a plain text file, which means, info should be set to the empty string.  I would add this as the first condition before line 446.  Python makes it very easy to be sloppy with types; it's good to always think about the semantics - difference between `{}, [], '', None`.

2017-01-08 22:42 UTC, kashizui commented
@percyliang We actually can't yet delete those lines since it is used by the legacy api. There may be a way to untangle it with some proper thought though.

2017-01-08 22:59 UTC, kashizui reviewed
I agree w/ Percy's comments.
Maybe it makes sense to require a file be nonempty to be considered a TSV file?

2017-01-10 08:50 UTC, maxwang7 commented
@percyliang @kashizui Thank you for the comments! I've made some changes that I believe are according to what was discussed. Some questions:
- I'm not understanding where the code checks for CSV or TSV files -- I've grep'd the repo and haven't found any useful keywords. Could someone explain to me how the code base checks for those things?
- Is the code I have written the proper we to type check for a Python list? I'm not sure whether to use isinstance() or `variable == []`.

2017-01-10 16:45 UTC, kashizui commented on codalab/lib/worksheet_util.py
> +            elif all('\t' in x for x in contents):
This is where the code checks that the file is a TSV

2017-01-10 16:46 UTC, kashizui requested changes

2017-01-10 16:46 UTC, kashizui commented on codalab/lib/worksheet_util.py
> +            if isinstance(contents, list) and len(contents) == 0:
`contents` should be guaranteed to be a list here, so no need to check its class.

2017-01-10 16:47 UTC, kashizui commented on codalab/lib/worksheet_util.py
> +            if isinstance(contents, list) and len(contents) == 0:
Just `if len(contents) == 0` or even just `if not contents` should be fine!

2017-01-12 09:42 UTC, maxwang7 commented
@kashizui Code has been updated. I would like to write a test for all of this, to do so, would I need to mock out everything that's used in interpret_file_genpath() though?

2017-01-12 22:06 UTC, kashizui approved these changes
LGTM modulo comment

2017-01-12 22:06 UTC, kashizui commented on codalab/lib/worksheet_util.py
> +              info = ''
use 4 spaces for indentation

2017-01-12 22:06 UTC, kashizui commented
@maxwang7 Yeah the way it is written now will make it hard to test since you would have to mock out the client. But it's only two method calls (get_target_info and head_target) so if it's easy to write up a test very quickly feel free to do so, but not necessary for now.

2017-01-12 22:10 UTC, percyliang commented on codalab/lib/worksheet_util.py
> +            if not contents: # contents is empty list
I would write `len(contents) == 0` and remove the comment...  Better to have code be more explicit and self-documenting.

2017-01-12 22:12 UTC, percyliang commented on codalab/lib/worksheet_util.py
> +              info = ''
You should make your editor default to 4 for Python.   Make sure you don't add tabs.  Indentation is really important to get right for Python!

2017-01-15 06:23 UTC, maxwang7 commented
I'm going to go ahead and merge. Tests will be written in a separate commit.

2017-01-15 06:24 UTC, merged