Stringify worksheet `frozen` field in wsearch directive results
codalab/codalab-worksheets pull request #629
Opened 2017-01-09 02:05 UTC by kashizui

Fixes codalab/codalab-worksheets#235 (stats on worksheets.codalab.org doesn't load)

Also ensure that future JSON serialization errors send us emails.

2017-01-09 02:07 UTC, kashizui commented
@percyliang I don't really like my current solution, where do you think would be the best place to make sure that 'frozen' is properly serialized?

2017-01-09 02:13 UTC, percyliang requested changes

2017-01-09 02:13 UTC, percyliang commented on codalab/rest/legacy.py
> +                info['frozen'] = str(info['frozen'])
I wouldn't use str()...use isoformat().

I think the `BundleModel` should be responsible for returning things back which are JSON serializable.  This method should not be looking at the internals of `results`.

2017-01-09 05:47 UTC, kashizui commented
+1 on isoformat().

I generally agree, but BundleModel.search_worksheets() is also used by code
that depends on datetime fields being actual datetime objects, so I had
avoided modifying the model method.
On Sun, Jan 8, 2017 at 18:13 Percy Liang <notifications@github.com> wrote:

> *@percyliang* requested changes on this pull request.
> ------------------------------
>
> In codalab/rest/legacy.py
> <https://github.com/codalab/codalab-cli/pull/629#pullrequestreview-15640358>
> :
>
> > @@ -145,6 +145,16 @@ def search_worksheets(keywords, worksheet_uuid=None):
>          keywords = resolve_owner_in_keywords(keywords)
>          results = local.model.search_worksheets(request.user.user_id, keywords)
>          BundleService._set_owner_names(results)
> +        # Hack: Make sure worksheet infos are JSON serializable.
> +        # Since this method is only used for worksheet interpretation (i.e.
> +        # resolving wsearch directives), these worksheet infos are never
> +        # serialized properly through WorksheetSchema or the Worksheet
> +        # ORMObject, and so the `frozen` attribute will cause a serialization
> +        # error when we attempt to serialize the interpretation results into
> +        # JSON.
> +        for info in results:
> +            if isinstance(info['frozen'], datetime):
> +                info['frozen'] = str(info['frozen'])
>
> I wouldn't use str()...use isoformat().
>
> I think the BundleModel should be responsible for returning things back
> which are JSON serializable. This method should not be looking at the
> internals of results.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codalab/codalab-cli/pull/629#pullrequestreview-15640358>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAlhtX5errrDUiW7IcW3KJNT6S4Z0vgMks5rQZfMgaJpZM4Ld4aE>
> .
>

2017-01-09 06:02 UTC, percyliang commented
We could just convert the isoformat string back to a datetime when we need it, although that's a bit backwards...

Alternatively, we can have a general utility function that converts any JSON object with datetimes (and perhaps other non-serializable types) into a serializable JSON?

2017-01-09 08:10 UTC, kashizui commented
@percyliang Pushed new changes that handles all datetime objects in JSON response objects. The `default` function handles any nonstandard objects that the JSON encoder encounters and cannot serialize.

2017-01-11 20:02 UTC, kashizui commented
@percyliang reminder to review again

2017-01-12 00:10 UTC, percyliang approved these changes
Nice LGTM

2017-01-12 05:20 UTC, merged