Alphabetize Permissions for legacy and REST APIs
codalab/codalab-worksheets pull request #653
Opened 2017-01-25 09:07 UTC by maxwang7

2017-01-25 15:26 UTC, percyliang reviewed
Can the sorting be done no in /rest/* but in bundle_model.py when you construct the worksheet_info and bundle_info objects?  That way, you only need the logic in one place.

Alternatively, this can be done on the frontend right before we display.

In general, putting conversion code at one of the two ends is better than in the middle, because then you just have to reason about one format most of the time.

2017-01-25 20:49 UTC, kashizui requested changes
Looking through the code now, it looks like the place to do this is in `BundleModel.batch_get_group_permissions()`. You might even be able to offload the sorting to MySQL in the query. 😛

2017-01-25 20:49 UTC, kashizui commented on codalab/rest/bundles.py
> +        bundle['group_permissions'] = sorted(bundle['group_permissions'], key=lambda x: x['group_name'])
This won't get included in the response, this line should go above the line that precedes it.

2017-01-25 20:56 UTC, maxwang7 commented on codalab/rest/bundles.py
> +        bundle['group_permissions'] = sorted(bundle['group_permissions'], key=lambda x: x['group_name'])
Ah, good to know. If I make the change to the BundleModel query though, I won't need this line anymore, right?

2017-01-25 20:59 UTC, kashizui commented on codalab/rest/bundles.py
> +        bundle['group_permissions'] = sorted(bundle['group_permissions'], key=lambda x: x['group_name'])
That's right sorry I made it confusing

2017-01-25 21:26 UTC, maxwang7 commented
I added an order_by statement in the batch_get_group_permissions() file. I want to do some more testing before committing these changes because something's not working locally for me.

Also, from my reading of the code, both the legacy API and the REST API use the same model, can someone confirm that? If so, I'll remove the other custom sorting functionality that I've written.

2017-01-25 21:39 UTC, kashizui commented
yep they use the same model
On Wed, Jan 25, 2017 at 13:26 maxwang7 <notifications@github.com> wrote:

> I added an order_by statement in the batch_get_group_permissions() file. I
> want to do some more testing before committing these changes because
> something's not working locally for me.
>
> Also, from my reading of the code, both the legacy API and the REST API
> use the same model, can someone confirm that? If so, I'll remove the other
> custom sorting functionality that I've written.
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/codalab/codalab-cli/pull/653#issuecomment-275237736>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAlhte0fN_7-WrdyzMTGPDhuHtHdreuvks5rV73sgaJpZM4LtPoU>
> .
>

2017-02-01 06:19 UTC, maxwang7 commented
@kashizui I've tested the changes and they're working in my test environment.

2017-02-01 08:15 UTC, kashizui approved these changes
LGTM modulo comment

2017-02-01 08:15 UTC, kashizui commented on codalab/rest/bundles.py
> +        bundle['group_permissions'] = sorted(bundle['group_permissions'], key=lambda x: x['group_name'])
Don't forget to delete this line!

2017-02-03 17:12 UTC, closed without merging