Support Local Development
codalab/codalab-worksheets pull request #660
Opened 2017-01-27 06:31 UTC by fabeschan

hi

2017-01-30 16:00 UTC, percyliang requested changes
This functionality is great!

- In general, more documentation would be nice.
- Can you update test-cli.py to test this functionality (which is also nice since it tells us what commands to use).
- When we add new CLI commands, we should really think through whether this is the best possible design and usage.  We should have several people test it and give comments before committing to it.
- In particular, I'm worried that we're adding too many functions at the top-level.  In some sense, `run-local` and `run-image` behave a lot like `run`, so those could be flags inside `run`.  Of course that has the danger of making `run` too bloated.  But this is something we should think about more and discuss.
- Usability: Before and after each of the commands runs, there should be more stuff printed to stdout saying what's going on and what to do next.
- Also, please use more meaningful commit messages.

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +        docker_image = metadata.get('request_docker_image', 'ubuntu:14.04')
I think If people are doing run-local, the `--request-docker-image` option should be required (they should be explicit about what they're doing.)  99% of the invocations will not be with `ubuntu:14.04`.

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +        bundle_path = '/opt/{}'.format(uuid)
Should not be `/opt`, but should be a flag that's passed in by the user.  Maybe default to the current directory?

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +        help='Create a bundle by running a program bundle on an input bundle.',
Needs to be updated to be more specific.

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +        help='Run a run bundle locally.',
Explain much more.

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +            Commands.Argument('--repository', help='Repository to commit to. E.g: codalabtest-on.azurecr.io/ubuntu', required=True),
Use dockerhub as an example

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +        help='Create a bundle by running a program bundle on an input bundle.',
More explanation.

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +        help='Create a bundle by running a program bundle on an input bundle.',
Update

2017-01-30 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +        for path1, path2 in dependencies:
use `name` and `child_path` (I think) to maintain consistency with code elsewhere.

2017-01-30 21:24 UTC, fabeschan commented
Hi @percyliang, thanks for looking through the changes. These are all good points, and the requested changes all make sense. However like you suggested let's hold a deeper discussion, think things through and settle into a more refined design before committing work to this.

Perhaps I can put together a google doc and we can take down some notes during upcoming meetings?

2017-01-30 21:43 UTC, percyliang commented
Sure.  I think we should aim to wrap this up this week (don't think we're
that far off).  And while we should think about it, I think there's no
substitute for rolling it out and getting people to try it (as long as it's
understood that this is a beta feature, we can still change the interface
after it goes into develop).

On Mon, Jan 30, 2017 at 1:24 PM, Fabian Chan <notifications@github.com>
wrote:

> Hi @percyliang <https://github.com/percyliang>, thanks for looking
> through the changes. These are all good points, and the requested changes
> all make sense. However like you suggested let's hold a deeper discussion,
> think things through and settle into a more refined design before
> committing work to this.
>
> Perhaps I can put together a google doc and we can take down some notes
> during upcoming meetings?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codalab/codalab-cli/pull/660#issuecomment-276195302>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAakuH5g9_o7_ht6Orufo_YRe5WL6SRIks5rXlUOgaJpZM4LveMh>
> .
>

2017-01-30 22:18 UTC, fabeschan commented
https://docs.google.com/document/d/1qELOtPOU6vbA2FtgOMmuBmRrVDGnNRszIgMW8s3XZl4/edit#heading=h.uuvhzjo8mk0y

2017-02-02 08:33 UTC, fabeschan commented on codalab/lib/bundle_cli.py
> +        bundle_path = '/opt/{}'.format(uuid)
Would it be better for bundle paths to be set in config? Having local bundles in one directory could make periodic clean-ups easier. If so, what path would be a good default?

2017-02-02 08:33 UTC, fabeschan commented on codalab/lib/bundle_cli.py
> +        docker_image = metadata.get('request_docker_image', 'ubuntu:14.04')
OK. I will require request-docker-image when running in local mode

2017-02-02 08:40 UTC, fabeschan commented
> In some sense, run-local and run-image behave a lot like run, so those could be flags inside run.

It makes sense to absorb run-local into run with a flag, but I'm feeling a bit queasy doing the same for run-image, which is meant for editing images (with some bells added to facilitate testing) but not for producing run bundles (with their contents).

I would prefer to keep them separate commands, but that's just my opinion. I'm not sure which way is best

2017-02-02 08:56 UTC, fabeschan commented
> Usability: Before and after each of the commands runs, there should be more stuff printed to stdout saying what's going on and what to do next.

Added more instructions to stdout where appropriate. Please review and let me know if there are more things I can mention @percyliang

2017-02-02 08:58 UTC, fabeschan commented
> update test-cli.py to test this functionality

Not exactly sure how to do this since some of the commands drop the user to a shell inside a container. Are there ways to run commands in the inner shell with python?

2017-02-03 17:12 UTC, closed without merging

2017-02-03 22:50 UTC, fabeschan commented on codalab/lib/bundle_cli.py
> +        bundle_path = '/opt/{}'.format(uuid)
@percyliang