Max help button
codalab/codalab-worksheets pull request #675
Opened 2017-02-06 05:09 UTC by maxwang7

Issue: https://github.com/codalab/codalab-worksheets/issues/251
Corresponding PR in codalab-worksheets: https://github.com/codalab/codalab-worksheets/pull/258

Creates a REST API endpoint that sends a support email.

These are features that I considered "extensions" -- let me know if any of them should be implemented for this PR:

- [ ] Creating a new SQL table that records all the messages that have been sent to us.
- [ ] Sending a "message received" email to the message sender's email.

2017-02-06 05:48 UTC, maxwang7 commented on codalab/rest/help.py
> +        body=template('help_message_to_codalab_body', username=username, email=support_email, message=message, sender=user_email),
For some reason setting the sender parameter isn't working for me -- it doesn't change who the sender is when I print it out. From my reading of [the email code](https://github.com/codalab/codalab-cli/blob/7e075ff3c4e3f4dc82ffb770382fc68feb90b0c2/codalab/lib/emailer.py#L84), though, it seems like it should work, even on the console.

2017-02-07 23:46 UTC, kashizui reviewed
Looks pretty good! Is this still a work in progress?

2017-02-07 23:46 UTC, kashizui commented on codalab/rest/help.py
> +    support_email = local.config['support_email']
What should happen if 'support_email' isn't defined in the config? Or should we require that 'support_email' always be defined?

2017-02-07 23:46 UTC, kashizui commented on codalab/rest/help.py
> +    return '{}'
Probably just don't return anything, unless you intend on adding data in the future. The frontend can just check the status code for success/failure.

If you want to return JSON data, you can just

    return {}

without the quotes.

2017-02-07 23:57 UTC, maxwang7 commented on codalab/rest/help.py
> +    support_email = local.config['support_email']
How have we dealt with similar kinds of configuration issues? I think we should require that it's always defined.

2017-02-07 23:57 UTC, maxwang7 commented on codalab/rest/help.py
> +    return '{}'
Ah, that sounds good, I just won't return then

2017-02-08 00:00 UTC, maxwang7 commented
Also, no, it's not meant to be a work in progress... unless you think there are more things that I should work on :)

2017-02-08 00:04 UTC, maxwang7 commented on codalab/rest/help.py
> +    return '{}'
Just fixed this in my latest commit

2017-02-08 00:12 UTC, kashizui commented on codalab/rest/help.py
> +    support_email = local.config['support_email']
Usually we try to provide a sane default when something is not defined, or just let it through with a warning message, unless it makes no sense to do so.

Example with the `admin_email` config:
https://github.com/codalab/codalab-cli/blob/master/codalab/server/rest_server.py#L200-L205

The issue is that requiring the config may cause a deployment to crash if we just forgot to update the config on the server. In this case it should be pretty isolated and not cause much problems though. Maybe we can just let this throw an exception to let us know we forgot to configure a support email, or throw your own exception to give a more helpful error message.

2017-02-08 00:17 UTC, kashizui requested changes

2017-02-08 00:17 UTC, kashizui commented on codalab/rest/help.py
> +    UserSchema,
clean up unused imports

2017-02-08 00:27 UTC, maxwang7 commented on codalab/rest/help.py
> +    UserSchema,
Done, thanks!

2017-02-08 00:30 UTC, kashizui commented
- i don't think there's a need for a sql table since we won't want to build an interface for viewing the table haha
- as long as the UI provides feedback on whether or not the message went through, it should be fine

2017-02-08 00:32 UTC, maxwang7 commented
Re SQL Table: Yeah, I was thinking that we may want to show users the messages that they've sent previously, and it may be a good next step to making this interface a more full-featured chat application. But I think that's a conversation for another day.

Re Message receive email: Ok, that seems reasonable.

2017-02-08 00:37 UTC, kashizui commented
If we want to make a more full-featured support ticket thing we might as well integrate with Zendesk.
Chat is probably a different story

2017-02-08 01:27 UTC, maxwang7 commented on codalab/rest/help.py
> +    support_email = local.config['support_email']
Ok, well why don't I just follow the pattern we've already established, and I'll just print off a message saying that the support_email needs to be configured, and then print of the email I would've sent to the console.

2017-02-08 01:36 UTC, maxwang7 commented on codalab/rest/help.py
> +    support_email = local.config['support_email']
Ok, changes made!

2017-02-08 01:37 UTC, kashizui requested changes
lgtm

do you know why the rest docs are showing up in the diff? They should be master already afaik..

2017-02-08 01:37 UTC, kashizui approved these changes

2017-02-08 21:58 UTC, maxwang7 commented
I'm not sure why or how they ended up here... I think I might've pull'd and they ended up in my this branch somehow. And sounds good, I'll merge.

2017-02-08 22:08 UTC, maxwang7 commented
Test this using SendGrid

2017-02-10 21:38 UTC, merged