Update `cl` list commands
codalab/codalab-worksheets pull request #691
Opened 2017-02-20 23:06 UTC by maxwang7

Uses do_command to call do_help_command
Issue: #686

2017-02-20 23:14 UTC, kashizui commented
This ends up breaking functionality for `cl <command> -h` or `cl <command> --help`, which should show just the help for a single command. What about just updating line 180 to call `do_command(...)`?

2017-02-22 22:06 UTC, kashizui requested changes
This ends up breaking functionality for `cl <command> -h` or `cl <command> --help`, which should show just the help for a single command. What about just updating line 180 to call `do_command(...)`?

2017-04-03 21:18 UTC, maxwang7 commented
I added an extra check so that `cl --help` and `cl -h` would both produce the help information as well. It feels a bit hacky but I couldn't find anywhere else that seemed more appropriate to add this code.

2017-04-03 22:43 UTC, percyliang approved these changes
Make sure all the variants of --help, help, -h with and without other commands work.

2017-04-03 22:43 UTC, percyliang commented on codalab/lib/bundle_cli.py
> -            self.print_help()
Can you delete `print_help` now?

2017-04-04 07:01 UTC, maxwang7 commented
Confirmed that all variants work. I tried these:

- `cl`
- `cl -h`
- `cl --help`
- `cl help`
- `cl add --help`
- `cl add -h`

2017-04-04 21:01 UTC, kashizui approved these changes

2017-04-04 23:17 UTC, merged