Add GPU worker support
codalab/codalab-worksheets pull request #695
Opened 2017-02-24 17:43 UTC by fabeschan

- [ ]  detect number of gpus on worker

- [ ] add gpu info to checkin request

- [ ] migrate database (add gpu column to worker table)

- [ ] add functionality to filter workers based on requested_gpus

2017-02-24 22:26 UTC, kashizui requested changes
Overall looks pretty good, and it works!

2017-02-24 22:26 UTC, kashizui commented on worker/worker.py
> +        container_id = self._docker.run_nvidia_smi('-L', 'gcr.io/tensorflow/tensorflow:latest-gpu')
I think we can use a more basic image than the tensorflow one? Maybe one of these:
https://hub.docker.com/r/nvidia/cuda/

2017-02-24 22:26 UTC, kashizui commented on worker/docker_client.py
> +    def run_nvidia_smi(self, args, docker_image):
I think I can see why but wondering what your reasoning was for running 'nvidia-smi' inside Docker rather than directly?

2017-02-27 21:29 UTC, fabeschan commented on worker/docker_client.py
> +    def run_nvidia_smi(self, args, docker_image):
I think in the future we're going to deploy workers as docker containers, in which case running `nvidia-smi` inside docker would not require us to have two different versions of worker images (one for gpu, one not) to deploy.

2017-02-28 02:10 UTC, fabeschan commented on worker/worker.py
> +        container_id = self._docker.run_nvidia_smi('-L', 'gcr.io/tensorflow/tensorflow:latest-gpu')
That's a great suggestion.

2017-02-28 02:11 UTC, fabeschan commented on worker/docker_client.py
> +    def run_nvidia_smi(self, args, docker_image):
Done!

2017-02-28 05:55 UTC, kashizui commented on worker/docker_client.py
> +    def run_nvidia_smi(self, args, docker_image):
Ah that's very inception-y to think about haha.

2017-02-28 05:56 UTC, kashizui approved these changes

2017-02-28 08:57 UTC, fabeschan commented on worker/docker_client.py
> +    def run_nvidia_smi(self, args, docker_image):
;)

2017-03-01 04:11 UTC, merged