Authless SMTP support
codalab/codalab-worksheets pull request #807
Opened 2017-10-23 17:24 UTC by krivard

Some SMTP servers don't require u/p authentication; these flags allow such a server to be used with CodaLab.

2017-10-24 06:12 UTC, maxwang7 commented on codalab/lib/codalab_manager.py
> +                password=self.config['email'].get('password',None),#['password'],
Could you remove everything that's commented out? And also add a comment describing why you made those changes (the description you wrote in the conversation is fine, i.e. "Some SMTP servers don't require u/p authentication; these flags allow such a server to be used with CodaLab.")

2017-10-24 06:15 UTC, maxwang7 reviewed
Thank you again for sending these in @krivard! I added some line level comments.

2017-10-24 06:15 UTC, maxwang7 commented on codalab/lib/emailer.py
> +        self.do_login = self.password != None
Add parentheses around the `self.password != None` part of the expression for clarity.

2017-10-24 06:15 UTC, maxwang7 commented on monitor.py
> +    sender_password = sender_info['password'] if 'password' in sender_info else None
Could you use the `dictionary.get()` function instead?

2017-10-24 07:02 UTC, fabeschan requested changes
Just some nits on style

2017-10-24 07:02 UTC, fabeschan commented on codalab/lib/emailer.py
> +            if self.do_login: mail_server.login(self.user, self.password)
nit: separate conditionals into two lines for clarity

2017-10-24 07:02 UTC, fabeschan commented on monitor.py
> +    if do_login: s.login(sender_user, sender_password)
ditto

2017-10-24 16:57 UTC, krivard commented
Cool, I think I fixed everything so far, though check that the comment/s are what you had in mind -- I  clarified the variation in monitor.py with a link but it might be overkill.

2017-10-29 07:28 UTC, merged

2017-10-29 07:28 UTC, maxwang7 commented
@krivard thank you for your contribution!