cl workers -- worker visibility
codalab/codalab-worksheets pull request #885
Opened 2018-03-11 08:01 UTC by fabeschan

2018-03-11 16:00 UTC, percyliang requested changes
This will be great to have!  We can follow up with mem,%cpu,disk reporting in a separate PR.

2018-03-11 16:00 UTC, percyliang commented on codalab/lib/bundle_cli.py
> +    ReadableDateTimeDelta,
Is this used?

2018-03-11 16:00 UTC, percyliang commented on codalab/client/json_api_client.py
> +    def get_worker_info(self):
rename to `get_workers_info` (plural); also applies to stuff in `bundle_cli.py`.

2018-03-11 16:00 UTC, percyliang commented on codalab/rest/workers.py
> +    if request.user.user_id != local.model.root_user_id:
Why is this commented out?

2018-03-11 16:00 UTC, percyliang commented on codalab/rest/workers.py
> +def worker_info():
`workers_info`

2018-03-18 09:55 UTC, fabeschan commented
Fixed nits

2018-03-18 10:06 UTC, merged